/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Scores = IDL.Record({
  'demoReadiness' : IDL.Nat,
  'stackMatch' : IDL.Nat,
  'docs' : IDL.Nat,
  'coverage' : IDL.Nat,
  'completeness' : IDL.Nat,
  'depth' : IDL.Nat,
  'aiUsage' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Alignment = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const RecruiterVerdict = IDL.Record({
  'why' : IDL.Text,
  'strengths' : IDL.Vec(IDL.Text),
  'emoji' : IDL.Text,
  'verdict' : IDL.Variant({
    'fail' : IDL.Null,
    'pass' : IDL.Null,
    'caution' : IDL.Null,
  }),
  'technical_debt' : IDL.Text,
  'criticalGaps' : IDL.Vec(IDL.Text),
});
export const EvaluationResult = IDL.Record({
  'applied_instructions' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'scores' : Scores,
  'summary' : IDL.Text,
  'missing_items' : IDL.Vec(IDL.Text),
  'final_score' : IDL.Nat,
  'timestamp' : Timestamp,
  'cached' : IDL.Bool,
  'red_flags' : IDL.Vec(IDL.Text),
  'project_type' : IDL.Text,
  'alignment' : Alignment,
  'recruiter_verdict' : IDL.Opt(RecruiterVerdict),
  'criticalGaps' : IDL.Vec(IDL.Text),
});
export const ExtractTextResult = IDL.Variant({
  'ok' : IDL.Record({ 'text' : IDL.Text, 'is_clean' : IDL.Bool }),
  'err' : IDL.Text,
});
export const EvaluationRecord = IDL.Record({
  'id' : IDL.Text,
  'result' : EvaluationResult,
  'owner' : IDL.Text,
  'assignment_text' : IDL.Text,
  'timestamp' : Timestamp,
  'repo_url' : IDL.Text,
});
export const RoleStats = IDL.Record({
  'avg_stack_match' : IDL.Nat,
  'avg_completeness' : IDL.Nat,
  'count' : IDL.Nat,
  'role' : IDL.Text,
  'avg_ai_usage' : IDL.Nat,
  'max_score' : IDL.Nat,
  'avg_score' : IDL.Nat,
  'min_score' : IDL.Nat,
  'avg_coverage' : IDL.Nat,
  'avg_depth' : IDL.Nat,
  'avg_demo' : IDL.Nat,
  'avg_docs' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearCache' : IDL.Func([], [], []),
  'deleteEvaluation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'evaluate' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(EvaluationResult)],
      [],
    ),
  'extractFileText' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Text],
      [ExtractTextResult],
      [],
    ),
  'extractNotesFileText' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Text],
      [ExtractTextResult],
      [],
    ),
  'fetchGoogleDocText' : IDL.Func([IDL.Text], [ExtractTextResult], []),
  'getCacheStats' : IDL.Func(
      [],
      [IDL.Record({ 'entries' : IDL.Nat, 'lastHit' : IDL.Bool })],
      [],
    ),
  'getEvaluationById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EvaluationResult)],
      ['query'],
    ),
  'getExportHistory' : IDL.Func([], [IDL.Vec(EvaluationRecord)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(EvaluationRecord)], ['query']),
  'getHistoryByRepo' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EvaluationRecord)],
      ['query'],
    ),
  'getRoleStats' : IDL.Func([], [IDL.Vec(RoleStats)], ['query']),
  'getVersion' : IDL.Func([], [IDL.Text], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Scores = IDL.Record({
    'demoReadiness' : IDL.Nat,
    'stackMatch' : IDL.Nat,
    'docs' : IDL.Nat,
    'coverage' : IDL.Nat,
    'completeness' : IDL.Nat,
    'depth' : IDL.Nat,
    'aiUsage' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Alignment = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const RecruiterVerdict = IDL.Record({
    'why' : IDL.Text,
    'strengths' : IDL.Vec(IDL.Text),
    'emoji' : IDL.Text,
    'verdict' : IDL.Variant({
      'fail' : IDL.Null,
      'pass' : IDL.Null,
      'caution' : IDL.Null,
    }),
    'technical_debt' : IDL.Text,
    'criticalGaps' : IDL.Vec(IDL.Text),
  });
  const EvaluationResult = IDL.Record({
    'applied_instructions' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'scores' : Scores,
    'summary' : IDL.Text,
    'missing_items' : IDL.Vec(IDL.Text),
    'final_score' : IDL.Nat,
    'timestamp' : Timestamp,
    'cached' : IDL.Bool,
    'red_flags' : IDL.Vec(IDL.Text),
    'project_type' : IDL.Text,
    'alignment' : Alignment,
    'recruiter_verdict' : IDL.Opt(RecruiterVerdict),
    'criticalGaps' : IDL.Vec(IDL.Text),
  });
  const ExtractTextResult = IDL.Variant({
    'ok' : IDL.Record({ 'text' : IDL.Text, 'is_clean' : IDL.Bool }),
    'err' : IDL.Text,
  });
  const EvaluationRecord = IDL.Record({
    'id' : IDL.Text,
    'result' : EvaluationResult,
    'owner' : IDL.Text,
    'assignment_text' : IDL.Text,
    'timestamp' : Timestamp,
    'repo_url' : IDL.Text,
  });
  const RoleStats = IDL.Record({
    'avg_stack_match' : IDL.Nat,
    'avg_completeness' : IDL.Nat,
    'count' : IDL.Nat,
    'role' : IDL.Text,
    'avg_ai_usage' : IDL.Nat,
    'max_score' : IDL.Nat,
    'avg_score' : IDL.Nat,
    'min_score' : IDL.Nat,
    'avg_coverage' : IDL.Nat,
    'avg_depth' : IDL.Nat,
    'avg_demo' : IDL.Nat,
    'avg_docs' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearCache' : IDL.Func([], [], []),
    'deleteEvaluation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'evaluate' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(EvaluationResult)],
        [],
      ),
    'extractFileText' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Text],
        [ExtractTextResult],
        [],
      ),
    'extractNotesFileText' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Text],
        [ExtractTextResult],
        [],
      ),
    'fetchGoogleDocText' : IDL.Func([IDL.Text], [ExtractTextResult], []),
    'getCacheStats' : IDL.Func(
        [],
        [IDL.Record({ 'entries' : IDL.Nat, 'lastHit' : IDL.Bool })],
        [],
      ),
    'getEvaluationById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EvaluationResult)],
        ['query'],
      ),
    'getExportHistory' : IDL.Func([], [IDL.Vec(EvaluationRecord)], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(EvaluationRecord)], ['query']),
    'getHistoryByRepo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EvaluationRecord)],
        ['query'],
      ),
    'getRoleStats' : IDL.Func([], [IDL.Vec(RoleStats)], ['query']),
    'getVersion' : IDL.Func([], [IDL.Text], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };