/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Alignment = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface EvaluationRecord {
  'id' : string,
  'result' : EvaluationResult,
  'owner' : string,
  'assignment_text' : string,
  'timestamp' : Timestamp,
  'repo_url' : string,
}
export interface EvaluationResult {
  'applied_instructions' : Array<string>,
  'scores' : Scores,
  'summary' : string,
  'missing_items' : Array<string>,
  'final_score' : bigint,
  'timestamp' : Timestamp,
  'cached' : boolean,
  'red_flags' : Array<string>,
  'project_type' : string,
  'alignment' : Alignment,
  'recruiter_verdict' : [] | [RecruiterVerdict],
}
export type ExtractTextResult = {
    'ok' : { 'text' : string, 'is_clean' : boolean }
  } |
  { 'err' : string };
export interface RecruiterVerdict {
  'why' : string,
  'emoji' : string,
  'verdict' : string,
  'technical_debt' : string,
}
export interface RoleStats {
  'avg_stack_match' : bigint,
  'avg_completeness' : bigint,
  'count' : bigint,
  'role' : string,
  'avg_ai_usage' : bigint,
  'max_score' : bigint,
  'avg_score' : bigint,
  'min_score' : bigint,
  'avg_coverage' : bigint,
  'avg_depth' : bigint,
  'avg_demo' : bigint,
  'avg_docs' : bigint,
}
export interface Scores {
  'stackMatch' : bigint,
  'demo' : bigint,
  'docs' : bigint,
  'coverage' : bigint,
  'completeness' : bigint,
  'depth' : bigint,
  'aiUsage' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'clearCache' : ActorMethod<[], undefined>,
  'deleteEvaluation' : ActorMethod<[string], boolean>,
  'evaluate' : ActorMethod<
    [Array<string>, string, [] | [string]],
    Array<EvaluationResult>
  >,
  /**
   * / Cache: evaluation results keyed by (repo_url | assignment_description)
   */
  'extractFileText' : ActorMethod<[Uint8Array, string], ExtractTextResult>,
  /**
   * / Persistent history store — survives canister upgrades via enhanced orthogonal persistence
   */
  'extractNotesFileText' : ActorMethod<[Uint8Array, string], ExtractTextResult>,
  'fetchGoogleDocText' : ActorMethod<[string], ExtractTextResult>,
  'getCacheStats' : ActorMethod<
    [],
    { 'entries' : bigint, 'lastHit' : boolean }
  >,
  'getEvaluationById' : ActorMethod<[string], [] | [EvaluationResult]>,
  'getExportHistory' : ActorMethod<[], Array<EvaluationRecord>>,
  'getHistory' : ActorMethod<[], Array<EvaluationRecord>>,
  'getHistoryByRepo' : ActorMethod<[string], Array<EvaluationRecord>>,
  'getRoleStats' : ActorMethod<[], Array<RoleStats>>,
  'getVersion' : ActorMethod<[], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];