/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EvaluationResult {
    applied_instructions: Array<string>;
    scores: Scores;
    summary: string;
    missing_items: Array<string>;
    final_score: bigint;
    timestamp: Timestamp;
    cached: boolean;
    red_flags: Array<string>;
    project_type: string;
    alignment: Alignment;
    recruiter_verdict?: RecruiterVerdict;
}
export type ExtractTextResult = {
    __kind__: "ok";
    ok: {
        text: string;
        is_clean: boolean;
    };
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface RecruiterVerdict {
    why: string;
    emoji: string;
    verdict: string;
    technical_debt: string;
}
export interface Scores {
    stackMatch: bigint;
    demo: bigint;
    docs: bigint;
    coverage: bigint;
    completeness: bigint;
    depth: bigint;
    aiUsage: bigint;
}
export interface RoleStats {
    avg_stack_match: bigint;
    avg_completeness: bigint;
    count: bigint;
    role: string;
    avg_ai_usage: bigint;
    max_score: bigint;
    avg_score: bigint;
    min_score: bigint;
    avg_coverage: bigint;
    avg_depth: bigint;
    avg_demo: bigint;
    avg_docs: bigint;
}
export interface EvaluationRecord {
    id: string;
    result: EvaluationResult;
    owner: string;
    assignment_text: string;
    timestamp: Timestamp;
    repo_url: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Alignment {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export interface backendInterface {
    clearCache(): Promise<void>;
    deleteEvaluation(id: string): Promise<boolean>;
    evaluate(repo_urls: Array<string>, assignment_description: string, optional_notes: string | null): Promise<Array<EvaluationResult>>;
    /**
     * / Cache: evaluation results keyed by (repo_url | assignment_description)
     */
    extractFileText(fileBytes: Uint8Array, fileName: string): Promise<ExtractTextResult>;
    /**
     * / Persistent history store — survives canister upgrades via enhanced orthogonal persistence
     */
    extractNotesFileText(fileBytes: Uint8Array, fileName: string): Promise<ExtractTextResult>;
    fetchGoogleDocText(url: string): Promise<ExtractTextResult>;
    getCacheStats(): Promise<{
        entries: bigint;
        lastHit: boolean;
    }>;
    getEvaluationById(id: string): Promise<EvaluationResult | null>;
    getExportHistory(): Promise<Array<EvaluationRecord>>;
    getHistory(): Promise<Array<EvaluationRecord>>;
    getHistoryByRepo(repo_url: string): Promise<Array<EvaluationRecord>>;
    getRoleStats(): Promise<Array<RoleStats>>;
    getVersion(): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Alignment as _Alignment, EvaluationRecord as _EvaluationRecord, EvaluationResult as _EvaluationResult, ExtractTextResult as _ExtractTextResult, RecruiterVerdict as _RecruiterVerdict, Scores as _Scores, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearCache(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCache();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCache();
            return result;
        }
    }
    async deleteEvaluation(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvaluation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvaluation(arg0);
            return result;
        }
    }
    async evaluate(arg0: Array<string>, arg1: string, arg2: string | null): Promise<Array<EvaluationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.evaluate(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.evaluate(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async extractFileText(arg0: Uint8Array, arg1: string): Promise<ExtractTextResult> {
        if (this.processError) {
            try {
                const result = await this.actor.extractFileText(arg0, arg1);
                return from_candid_ExtractTextResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extractFileText(arg0, arg1);
            return from_candid_ExtractTextResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async extractNotesFileText(arg0: Uint8Array, arg1: string): Promise<ExtractTextResult> {
        if (this.processError) {
            try {
                const result = await this.actor.extractNotesFileText(arg0, arg1);
                return from_candid_ExtractTextResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extractNotesFileText(arg0, arg1);
            return from_candid_ExtractTextResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchGoogleDocText(arg0: string): Promise<ExtractTextResult> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGoogleDocText(arg0);
                return from_candid_ExtractTextResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGoogleDocText(arg0);
            return from_candid_ExtractTextResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCacheStats(): Promise<{
        entries: bigint;
        lastHit: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCacheStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCacheStats();
            return result;
        }
    }
    async getEvaluationById(arg0: string): Promise<EvaluationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvaluationById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvaluationById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExportHistory(): Promise<Array<EvaluationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExportHistory();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExportHistory();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistory(): Promise<Array<EvaluationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoryByRepo(arg0: string): Promise<Array<EvaluationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryByRepo(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryByRepo(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoleStats(): Promise<Array<RoleStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoleStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoleStats();
            return result;
        }
    }
    async getVersion(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVersion();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Alignment_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alignment): Alignment {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_EvaluationRecord_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvaluationRecord): EvaluationRecord {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EvaluationResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvaluationResult): EvaluationResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ExtractTextResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtractTextResult): ExtractTextResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EvaluationResult]): EvaluationResult | null {
    return value.length === 0 ? null : from_candid_EvaluationResult_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecruiterVerdict]): RecruiterVerdict | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    result: _EvaluationResult;
    owner: string;
    assignment_text: string;
    timestamp: _Timestamp;
    repo_url: string;
}): {
    id: string;
    result: EvaluationResult;
    owner: string;
    assignment_text: string;
    timestamp: Timestamp;
    repo_url: string;
} {
    return {
        id: value.id,
        result: from_candid_EvaluationResult_n3(_uploadFile, _downloadFile, value.result),
        owner: value.owner,
        assignment_text: value.assignment_text,
        timestamp: value.timestamp,
        repo_url: value.repo_url
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applied_instructions: Array<string>;
    scores: _Scores;
    summary: string;
    missing_items: Array<string>;
    final_score: bigint;
    timestamp: _Timestamp;
    cached: boolean;
    red_flags: Array<string>;
    project_type: string;
    alignment: _Alignment;
    recruiter_verdict: [] | [_RecruiterVerdict];
}): {
    applied_instructions: Array<string>;
    scores: Scores;
    summary: string;
    missing_items: Array<string>;
    final_score: bigint;
    timestamp: Timestamp;
    cached: boolean;
    red_flags: Array<string>;
    project_type: string;
    alignment: Alignment;
    recruiter_verdict?: RecruiterVerdict;
} {
    return {
        applied_instructions: value.applied_instructions,
        scores: value.scores,
        summary: value.summary,
        missing_items: value.missing_items,
        final_score: value.final_score,
        timestamp: value.timestamp,
        cached: value.cached,
        red_flags: value.red_flags,
        project_type: value.project_type,
        alignment: from_candid_Alignment_n5(_uploadFile, _downloadFile, value.alignment),
        recruiter_verdict: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.recruiter_verdict))
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): Alignment {
    return "Low" in value ? Alignment.Low : "High" in value ? Alignment.High : "Medium" in value ? Alignment.Medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        text: string;
        is_clean: boolean;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        text: string;
        is_clean: boolean;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvaluationRecord>): Array<EvaluationRecord> {
    return value.map((x)=>from_candid_EvaluationRecord_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvaluationResult>): Array<EvaluationResult> {
    return value.map((x)=>from_candid_EvaluationResult_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
